const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error('❌ Missing SUPABASE_URL or SUPABASE_SERVICE_KEY in .env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

async function restore() {
  const backupFile = process.argv[2];
  const adminUser = process.argv[3] || 'SystemAdmin';
  
  if (!backupFile) {
    console.error('❌ Please provide a backup file path. Example: node restore_db_full.cjs server/db/backups/backup-123.json');
    process.exit(1);
  }
  
  const absolutePath = path.resolve(__dirname, backupFile);
  if (!fs.existsSync(absolutePath)) {
    console.error(`❌ Backup file not found at: ${absolutePath}`);
    process.exit(1);
  }
  
  console.log(`🔄 Reading backup file from: ${absolutePath}`);
  const raw = fs.readFileSync(absolutePath, 'utf-8');
  const backupData = JSON.parse(raw);
  
  const tables = ['users', 'products', 'orders', 'logs', 'cms', 'promos'];
  
  for (const table of tables) {
    const records = backupData[table];
    if (!records || records.length === 0) {
      console.log(`⏭️  Skipping ${table}: No records found in backup.`);
      continue;
    }
    
    console.log(`\n🗑️  Clearing existing data from ${table}...`);
    // Delete all records where id is not an empty UUID (effectively deletes everything since IDs are autogenerated)
    // For cms table, the primary key is 'type'.
    const pk = table === 'cms' ? 'type' : 'id';
    const { error: deleteError } = await supabase.from(table).delete().neq(pk, table === 'cms' ? 'unknown_type_xxx' : '00000000-0000-0000-0000-000000000000');
    
    if (deleteError) {
      console.error(`❌ Failed to clear ${table}:`, deleteError.message);
      process.exit(1);
    }
    console.log(`   ✓ Cleared ${table}.`);
    
    console.log(`📥 Restoring ${records.length} records to ${table}...`);
    const BATCH_SIZE = 50;
    let inserted = 0;
    
    for (let i = 0; i < records.length; i += BATCH_SIZE) {
      const batch = records.slice(i, i + BATCH_SIZE);
      const { error: insertError } = await supabase.from(table).insert(batch);
      
      if (insertError) {
        console.error(`❌ Failed to insert batch into ${table}:`, insertError.message);
        process.exit(1);
      }
      inserted += batch.length;
      console.log(`   ✓ Inserted ${inserted}/${records.length} into ${table}...`);
    }
  }
  
  // Log the restoration
  const filename = path.basename(absolutePath);
  await supabase.from('logs').insert([{
    user: adminUser,
    action: `Restored database from backup file: ${filename}`
  }]);
  
  console.log('\n🎉 Full database restore complete!');
}

restore().catch(err => {
  console.error('❌ Unexpected error during restore:', err);
  process.exit(1);
});
